<?php

return [
    "retailer" => "تاجر تجزئة",
    "wholesale" => "جملة",
    "transfer" => "تحويل",
    "refund" => "استرداد",
    "paid" => "مدفوع",
    "gift" => "هدية",
    "recharge" => "إعادة شحن",
    "default" => "افتراضي",
    "customer" => "زبون",
    "inside_office" => "داخل المكتب",
    "outside_office" => "خارج المكتب",
    "deposit" => "إيداع",
    "withdraw" => "سحب",
    'textarea' => "حقل نصي",
    'excel_file' => "ملف إكسل",
    'text_file' => "ملف نصي",
    "paid" => "مدفوع",
    "unpaid" => "غير مدفوع",
    "topupPhone" => "إعادة شحن الهاتف",
    "percent" => "نسبة مئوية",
    "fixed" => "ثابت",
    "in_review" => "قيد المراجعة",
    "processing" => "قيد المعالجة",
    "completed" => "مكتمل",
    "digital" => "رقمي",
    "physical" => "مادي",
    "supermarchet" => "سوبر ماركت",
    "gsm_mobile" => "جهاز جوال GSM",
    "tabac_cosmetique" => "توباكو ومستحضرات التجميل",
    "magasin_satellite" => "متجر أقمار صناعية",
    "magasin_bureau_d_informatique" => "متجر مكتب حواسيب",
    "librairie" => "مكتبة",
    "cyber_cafe" => "مقهى إنترنت",
    "pending" => "معلق",
    "canceled" => "ملغى",
    "on_hold" => "معلق",
    "refunded" => "تم استرداده",
    "pending_payment" => "دفع معلق",
    "database" => "قاعدة بيانات",
    "larafcm" => "إشعارات الدفع الفوري",
    "mail" => "البريد",
    "mobilis"  => "موبليس",
    "djezzy" => "جازي",
    "ooredoo" => "أوريدو"
];
