<?php

return [
    "retailer" => "Retailer",
    "wholesale" => "Wholesale",
    "transfer" => "Transfer",
    "refund" => "Refund",
    "paid" =>   "Paid",
    "gift" => "Gift",
    "recharge" => "Recharge",
    "default" => "Default",
    "customer" => "Customer",
    "inside_office" => "Inside Office",
    "outside_office" => "Outside Office",
    "deposit" => "Deposit",
    "withdraw" => "Withdraw",
    'textarea' => "Textarea",
    'excel_file' => "Excel File",
    'text_file' => "Text File",
    "paid" => "Paid",
    "unpaid" => "Unpaid",
    "topupPhone" => "Top-Up Phone",
    "percent" => "Percent",
    "fixed" => "Fixed",
    "in_review" => "In-Review",
    "processing" => "Processing",
    "completed" => "Completed",
    "digital" => "Digital",
    "physical" => "Physical",
    "supermarchet" => "Supermarchet",
    "gsm_mobile" => "Gsm Mobile",
    "tabac_cosmetique" => "Tabac & Cosmetique",
    "magasin_satellite" => "Magasin Satellite",
    "magasin_bureau_d_informatique" => "Magasin Bureau D'informatique",
    "librairie" => "Librairie",
    "cyber_cafe" => "Cyber Cafe",
    "pending" => "Pending",
    "canceled" => "Canceled",
    "on_hold" => "On Hold",
    "refunded" => "Refunded",
    "pending_payment" => "Pending Payment",
    "database" => "Database",
    "larafcm" => "Push Notification",
    "mail" => "Mail",
    "mobilis"  => "Mobilis",
    "djezzy" => "Djezzy",
    "ooredoo" => "Ooredoo"
];
