<?php

return [
    "retailer" => "Détaillant",
    "wholesale" => "Vente en gros",
    "transfer" => "Transfert",
    "refund" => "Remboursement",
    "paid" => "Payé",
    "gift" => "Cadeau",
    "recharge" => "Recharge",
    "default" => "Défaut",
    "customer" => "Client",
    "inside_office" => "Dans le bureau",
    "outside_office" => "En dehors du bureau",
    "deposit" => "Dépôt",
    "withdraw" => "Retrait",
    'textarea' => "Zone de texte",
    'excel_file' => "Fichier Excel",
    'text_file' => "Fichier texte",
    "paid" => "Payé",
    "unpaid" => "Non payé",
    "topupPhone" => "Recharge de téléphone",
    "percent" => "Pourcentage",
    "fixed" => "Fixe",
    "in_review" => "En révision",
    "processing" => "En traitement",
    "completed" => "Terminé",
    "digital" => "Numérique",
    "physical" => "Physique",
    "supermarchet" => "Supermarché",
    "gsm_mobile" => "Téléphonie mobile",
    "tabac_cosmetique" => "Tabac & Cosmétique",
    "magasin_satellite" => "Magasin Satellite",
    "magasin_bureau_d_informatique" => "Magasin de bureau informatique",
    "librairie" => "Librairie",
    "cyber_cafe" => "Cyber Café",
    "pending" => "En attente",
    "canceled" => "Annulé",
    "on_hold" => "En attente",
    "refunded" => "Remboursé",
    "pending_payment" => "Paiement en attente",
    "database" => "Base de données",
    "larafcm" => "Notification Push",
    "mail" => "Mail",
    "mobilis" => "Mobilis",
    "djezzy" => "Djezzy",
    "ooredoo" => "Ooredoo"
];
